### ISSUE TITLE
named subs?

### ISSUE THREAD

**Issue by ownwaterloo** [wolfgangj/bone-lisp#19]
The doc says:

> we only add a shortcut for _anonymous_ subs with a single expression in the body...

Are there non-anonymous(or _named_) subs(like `(fn f [x] ...)` in Clojure) in bone?
It can't be done by lambda or subs shortcut right?
If it is the case, is it better to remove the word "anonymous" in the doc?

**Comment by wolfgangj** [comment]
Good catch. Since it is possible to do `(mysub f | x (...))` (similar to how `define` works in Scheme), it is not only for anonymous subs.

Creating a function/subroutine and giving it a name have always been orthogonal operations in the Lisp tradition and I think this is the right thing. The equivalent of your Clojure example would be `(with f | x (...) f)`, which certainly is a candidate for a macro.

**Comment by ownwaterloo** [comment]
The original statement could lead to (at least) two interpretations:
1. There are anonymous and named subroutines, shortcut is for some of them(anonymous and with a single expression in the body).
2. All subroutines are anonymous, shortcut is for some of them(with a single expression in the body).

I think the latter is correct and the word "anonymous" in that statement is confusing. It's better to remove it. That's my point.

About `(fn f [x] ...)` in Clojure, I'm not saying "bone or other lisps should support this" or something like that. I just need it to explain the opposite of anonymous subroutines.

**Comment by ownwaterloo** [comment]
clicked on the wrong button.

**Comment by wolfgangj** [comment]
Yes, you're right, I'm going to remove it. Thanks. :)
